# docker compose file version
version: '3'

# all of your services list will define here
services: 

    mongoDb: #serviceName
        image: mongo #get mongoDb latest image from hub.docker.com
        restart: always  # our services will runs continuously and will not stop until we stop this
        environment: # initialize mongoDb with ROOT username and password
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=example
        # in docker evironment, data is not persistant, so we used volumes to persist data
        # volumes are managed by docker and it is a persistant storage
        volumes: 
            - db-volume:/data/db  
        

    backend:   
        build: # build image
            context: ./backend #directory location
            dockerfile: Dockerfile # dockerfile name
        volumes: 
            - /app/node_modules
            - ./backend:/app    
        environment: 
             # this url mean, when you want to connect to other container inside the container without exposing the port, you need other 
             # container service name and port on which it is running
            - MONGODB_URI=MONGODB_URI=mongodb://root:example@mongoDb:27017/dockerizingMernApplicationTestDB?authSource=admin
            - CHOKIDAR_USEPOLLING=true #for hot reloading
           
        depends_on:  # don't run untill mongoDb service will not start 
            - mongoDb   
        restart: always    

    frontend:   
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        restart: always    
        volumes: 
            - /app/node_modules # we reference the node_modules which is present in app directory inside the docker, to our current node modules which is present in front directory
            - ./frontend:/app  # frontend directory is used as a volume(bind mount)  
             
        environment: 
            #request will forward to same url, so we only need /api so our nginx distinguish that this request will forward to our backend    
            - REACT_APP_BACKEND_URL=/api
            - CHOKIDAR_USEPOLLING=true
    
    nginx:
        image: linuxserver/swag
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/config:/config
            - ./nginx/default.conf:/config/nginx/site-confs/default.conf
            - ./nginx/ssl.conf:/config/nginx/ssl.conf
        container_name: nginx
        restart: unless-stopped
        environment: 
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - URL=devvtutorial.ml
            - SUBDOMAINS=www,
            - VALIDATION=http
            - STAGING= false #optional 
            - EMAIL=dijes29341@asmm5.com

        # volumes are defined here
volumes: 
    db-volume: